dbus-fuzzer/dfuzzer

src/Makefile

The mainline version didn't compile on Ubuntu but I fixed this by changing the ordering of compiler arguments. The root of the problem was that libraries to link came before object files, which caused the linker to ignore the libraries (as there was nothing to link them to) and then fail on an attempt to link the objects without the libraries (due to unresolved references). With this ordering, everything seems to work fine: we link the object files to the libraries, references are resolved and dfuzzer can start as expected.

Fix compilation bug

---

scripts/reprogen.py
src/fuzz.c

This is a simple Python 3 script which generates either dbus-send or gdbus commands (depending on command-line switches) to reproduce crashes. It can take input from files or stdin, is quite configurable and generally seems to work well.
Issues and possible improvements:
+ sometimes the logs get malformed and we get too many interface names and object paths; the generator can deal with that, but this is somewhat of a hack. I'm not sure why it happens but I assume that it's because a function that ```df_fuzz_write_log()``` is skipped or exits early for some reason
+ the output assumes that we will be calling dbus-send/gdbus with a shell and decodes hex strings by ```echo```ing them, piping that to ```xxd``` and inserting the output into the call. I'm not sure if xxd is an acceptable …

Reproducer generator

---

src/dfuzzer.c

Extend file_path[20] to file_path[25]. Because
max5chars is too short for pid sometimes.
Signed-off-by: Zhu Huankai <283014003@qq.com>

dfuzzer.c：modify df_open_proc_status_file

---

src/dfuzzer.c

When running from a systemd service (or any other environment where
$HOME is not set) dfuzzer crashes when it attempts to load the
suppression file. Let's skip the $HOME-bound suppression file checks in
such cases to avoid that.
Reproducer:
```
Running as unit: run-u51.service
Finished with result: core-dump
Main processes terminated with: code=dumped/status=SEGV
Service runtime: 104ms
CPU time consumed: 3ms
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f51857434bd in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x000055b3a1d55375 in df_load_suppressions () at dfuzzer.c:1243
#2  0x000055b3a1d5352f in main (argc=<optimized out>, argv=<optimized out>) at dfuzzer.c:116
```

Don't crash when $HOME is unset

---

src/dfuzzer.c

Properly terminate the suppression strings

---

src/dfuzzer.c
src/dfuzzer.h
src/fuzz.c

This prevents dfuzzer to output ANSI escape sequences to stdout/stderr
when the target doesn't support them (i.e. when redirected into a file
or when running as a systemd service logging into a journal).
/cc @matusmarhefka, @evverx

Don't print ANSI sequences when not on a tty

---

src/dfuzzer.c
src/dfuzzer.h

Today's `kernel.pid_max=` is usually set to 2^22 (4194304) instead of
the original 2^16 (65535), causing buffer overflow when trying to write
`/proc/<PID>/cmdline` into the stack-allocated buffer. Let's fix this by
using the maximum "string length" of int (calculated using a macro
borrowed from systemd, which might be useful in the future).
Fixes: #11

Account for kernel.pid_max > 65535

---

.packit.yaml

to make sure the package is buildable on various architectures.

ci: turn on Packit

---

src/dfuzzer.conf

dfuzzer doesn't poke void methods yet but once https://github.com/matusmarhefka/dfuzzer/issues/18
is implemented all those methods should be blocked.
It should help to somewhat cover the code parsing dfuzzer.conf on GHActions
with sanitizers though.

dfuzzer.conf: add more destructive systemd methods

---

meson.build
src/Makefile
src/dfuzzer.c
src/introspection.c
src/introspection.h
src/rand.c

The code annotations for `rand()` and `random()` feel a bit icky (I wish there was an option to disable the warning for the whole file), but it is what it is. I guess the other option would be to suppress them manually in the UI.
The remaining Coverity warnings will require a bit more work.
Also, this fixes #30 - the `name` parameter was originally used just in the error paths, but the `name` argument was dropped in 15a6d7b9f60269fdf5e3febb61eb45e481873a8c, so was completely unused since then.

A couple more Coverity-related tweaks

---

.lgtm.yml

LGTM can detect meson projects automatically

ci: switch to meson on LGTM as well

---

.github/workflows/build.yml
.github/workflows/run-tests.sh
src/fuzz.c

and two memory leaks were fixed along the way
```sh
22,255 (3,456 direct, 18,799 indirect) bytes in 72 blocks are definitely lost in loss record 1,096 of 1,096
at 0x484486F: malloc (vg_replace_malloc.c:381)
by 0x4AF7428: g_malloc (gmem.c:106)
by 0x4B10074: g_slice_alloc (gslice.c:1072)
by 0x4B2F772: UnknownInlinedFun (gvariant-core.c:486)
by 0x4B2F772: UnknownInlinedFun (gvariant-core.c:624)
by 0x4B2F772: g_variant_builder_end (gvariant.c:3725)
by 0x4B32FA3: g_variant_valist_new (gvariant.c:5236)
by 0x4B33571: g_variant_new_va (gvariant.c:5409)
by 0x4B336C3: g_variant_new (gvariant.c:5344)
by 0x4BDEC03: ffi_call_unix64 (unix64.S:76)
by 0x4BDE107: ffi_call (ffi64.c:525)
by 0x4056D6: df_fuzz_create_variant (fuzz.c:798)
by 0x40643C: df_fuzz_test_method (fuzz.c:576)
by 0x403FDD: df_fuzz …
```

ci: run dfuzzer under Valgrind as well

---

.github/dependabot.yml

Judging by https://github.com/evverx/dfuzzer/pull/4 they are already out of date

ci: let Dependabot keep track of actions

---

.github/workflows/run-tests.sh
src/fuzz.c

It should temporarily address https://github.com/matusmarhefka/dfuzzer/issues/45
This reverts commit 1c7753a9730d6d0add98b169f8ec32061e90d2ce.

Revert "fix a huge memory leak"

---

.github/workflows/run-tests.sh
src/dfuzzer.c
src/dfuzzer.conf

Resolves: #43
---
CI didn't catch this, since we only tested `dfuzzer -s -l`, i.e. skipping the suppression part.

dfuzzer: skip loading suppressions when no proc name is specified

---

.github/workflows/build.yml
meson.build
src/dfuzzer-test-server.c

Also, since the test-server code uses many callback functions with
unused parameters, let's compile just the server with
`-Wno-unused-parameter`, so we don't have to pollute the code with the
`__attribute__((__unused__))` stuff.

test-server: make the test-server compatible with -Werror

---

.github/workflows/run-tests.sh
src/fuzz.c
src/util.h

Let's keep reference only to the last created GVariant, since it's
needed later in the `df_fuzz_write_log()` function.
Resolves: #45
---
Slightly better version of https://github.com/matusmarhefka/dfuzzer/pull/47.

fuzz: avoid leaking memory

---

.github/workflows/run-tests.sh
src/dfuzzer.c
src/dfuzzer.conf
src/fuzz.c
src/rand.c
src/rand.h

This is a quick & dirty tweak to see if we can probe void methods
(methods without arguments) as soon as possible, since it proved to be
quite useful.
Resolves: #18

dfuzzer: probe void methods as well

---

.github/workflows/run-tests.sh
src/dfuzzer.c
src/dfuzzer.h

Since we can't use any well-known remote method for auto-activation, fall
back to calling the org.freedesktop.DBus.StartServiceByName method.
See:
- https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-start-service-by-name
- https://dbus.freedesktop.org/doc/system-activation.txt
Resolves: #55

dfuzzer: attempt to activate the remote side

---

.github/workflows/build.yml
.github/workflows/run-tests.sh
src/dfuzzer-test-server.c
src/dfuzzer.c
src/dfuzzer.conf
src/dfuzzer.h
src/fuzz.c
src/fuzz.h
src/util.h

as it interferes with other means of detecting memory leaks (Valgrind,
AddressSanitizer, etc.)
(Still very WIP, I'm just curious what I've managed to break so far)

fuzz: drop the leak detection code

---

.github/workflows/run-tests.sh
.lgtm.yml
README.md
meson.build
src/Makefile
src/dfuzzer-test-server.c
src/dfuzzer.c
src/dfuzzer.conf
src/dfuzzer.h
src/fuzz.c
src/fuzz.h
src/introspection.c
src/introspection.h
src/rand.c
src/rand.h
src/util.c
src/util.h

fuzz: handle advanced signatures as well

---

src/fuzz.c

This got accidentally omitted during the latest rewrite.
Addresses: https://github.com/matusmarhefka/dfuzzer/pull/64#issuecomment-1120242055

fuzz: log the method name as well

---

.github/workflows/run-tests.sh
man/dfuzzer.xml
src/dfuzzer-test-server.c
src/dfuzzer.c
src/rand.c
src/rand.h

@evverx possible solution for https://github.com/systemd/systemd/issues/23312#issuecomment-1120441314.
One downside which comes to mind is that you can't specify strings with newlines, since the newline is used as a separator. If that would be an issue, I'd have to come up with a different solution.

dfuzzer: allow specifying a custom set of input strings

---

src/dfuzzer.conf
src/fuzz.c

I'm actually baffled how I managed to miss this, but thanks to sheer
luck the crashes were getting detected, albeit a bit later (when dfuzzer
detected the remote PID disappeared). All this surfaced once I was
trying to dump a reproducer for each specific fail/crash, and was
getting wrong values (i.e. values from a couple of iterations later).
tl;dr we ignored when the method returned no reply or timed out.

fuzz: check the method call return code as well

---

.github/workflows/run-tests.sh
src/dfuzzer-test-server.c
src/dfuzzer.c
src/dfuzzer.conf
src/fuzz.c
src/fuzz.h
src/introspection.c
src/introspection.h

So we don't expect a reply from a method which intentionally doesn't
respond.
---
Tested on Rawhide and it seems to DTRT:
```
[SESSION BUS]
Bus not found.
[SYSTEM BUS]
[PROCESS: /usr/lib/systemd/systemd]
[CONNECTED TO PID: 1]
Object: /org/freedesktop/systemd1
Interface: org.freedesktop.systemd1.Manager
PASS Reexecute
Exit status: 0
```

fuzz: respect the `org.freedesktop.DBus.Method.NoReply` annotation

---

man/dfuzzer.xml
src/dfuzzer-test-server.c
src/fuzz.c

Also, reorder the for/loop statements, because I have no idea why I put
them like I did in the first place, and check if the remote side is
alive even after just reading a property.
```
Interface: org.freedesktop.dfuzzerInterface
PASS [P] read_only (read)
PASS [P] write_only (write)
FAIL [P] crash_on_write (write) - unexpected response while writing to a property
[RE-CONNECTED TO PID: 2479535]
PASS [P] read_write (read)
PASS [P] read_write (write)
PASS [M] df_hello
...
```
Addresses: https://github.com/matusmarhefka/dfuzzer/pull/86#pullrequestreview-971808731

fuzz: distinguish between reading/writing properties in logs

---

src/fuzz.c
src/rand.c
src/rand.h

if the signature contains an array.

fuzz: generate an empty array on the first iteration

---

.github/workflows/run-tests.sh
src/dfuzzer.conf

Ref*, Unref* and Thaw* aren't destructive. They just trigger various issues in systemd. All those issues have been fixed upstream so it should be safe to unblock them.

update systemd suppressions

---

src/bus.c
src/dfuzzer.c
src/dfuzzer.h

Also, simplify the D-Bus error handling by always dumping the remote
error code.
Resolves: #98

dfuzzer: bail out on any D-Bus error while traversing the tree

---

src/bus.c
src/dfuzzer-test-server.c
src/dfuzzer.c
src/fuzz.c
src/fuzz.h
src/introspection.c
src/rand.c
src/util.h

GLib already implements a lot of helpers I brought over from systemd, so let's use them to make the code base shorter and more unified.

Use GLib helpers instead of our own where possible

---

src/dfuzzer.conf

Once this method is called dfuzzer can no longer send messages and
bails out with
```
PASS [M] Introspect
Interface: org.freedesktop.DBus.Monitoring
PASS [M] BecomeMonitor
Interface: org.freedesktop.DBus.Peer
Error: Unable to create proxy for bus name 'org.freedesktop.DBus'.
Exit status: 1
```
https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-become-monitor

dfuzzer.conf: suppress BecomeMonitor

---

src/fuzz.c

Which got accidentally introduced in ae01b1b67a6744efc5bb0c75a4986792faf6a4ad.

fuzz: drop leftover debug printf()

---

src/rand.c

G_N_ELEMENTS() returns the length of the array including the NUL
byte, which means we'd randomly terminate the signature while
generating it, making it way shorter than it should be.
---
I'm working on making the signature generation *generic* to generate arbitrary signatures, but in the meantime let's fix at least this bug I noticed along the way.

rand: don't randomly truncate the pseudo-random signatures

---

src/rand.c
src/rand.h

and simplify the code a bit.
According to the D-Bus spec, the object path might be of arbitrary
length, can contain arbitrary amount of elements (but at least one), and
can begin with any of the allowed characters.

rand: loosen the rules for the pseudo-random object paths

---

src/bus.c
src/dfuzzer.c
src/dfuzzer.h
src/fuzz.c
src/fuzz.h
src/log.c
src/log.h
src/meson.build

Decouple the logging stuff from the main dfuzzer file and simplify it a
bit.
This is the first of several necessary steps to allow introducing unit
tests for dfuzzer's internal functions.

tree-wide: move logging stuff into a separate file

---

src/dfuzzer.c
src/fuzz.c
src/introspection.c
src/rand.c
src/util.c

Let's use g_assert() everywhere instead of "plain" assert().

tree-wide: unify asserts

---

man/dfuzzer.xml
src/dfuzzer.c
src/fuzz.c
src/fuzz.h
src/util.c
src/util.h
test/meson.build
test/test-util.c

Explicitly use fork() & execl() to avoid the file descriptor
shenanigans, and move & rename the function to util.[ch].
Also, when at it, add a unit test for the function as well.

fuzz: rework df_exec_cmd_check()

---

.packit.yaml

since the unit tests are now part of the Rawhide spec file.
See: https://src.fedoraproject.org/rpms/dfuzzer/c/dc958e7916ad4db426a79a059947fd72986fc11c?branch=rawhide

packit: drop the meson_test related sed

---

.github/workflows/build.yml

This also replaces the deprecated `path-to-lcov` with `file`, and adds a now semi-required `format` parameter [0].
Supersedes: #127
[0] https://github.com/coverallsapp/github-action/blob/release/v2/UPGRADE.md#v1---v2

ci: update Coveralls to v2.0.0

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/coverity.yml
src/rand.c

```
[11/28] Compiling C object dfuzzer.p/src_rand.c.o
../src/rand.c:541:17: warning: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Wstring-concatenation]
"%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n",
^
../src/rand.c:540:17: note: place parentheses around the string literal to silence warning
"%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n%n" \
^
1 warning generated.
```
Reported in https://github.com/dbus-fuzzer/dfuzzer/pull/63#issuecomment-1731324397
---
Also, let's switch all CI jobs to use the ubuntu-latest images, so we don't have to bump them manually (and so we're not stuck with old stuff when we forgot, like we did with the build job).

rand: appease clang-12 and later

---

meson.build

Apart from looking way nicer, it also gets rid of a deprecation warning with meson >= 1.3.0:
```
...
Configuring config.h using configuration
meson.build:75: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.3.0': str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof.. Build targets in project: 3
WARNING: Broken features used:
* 1.3.0: {'str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof.'}
```
Docs: https://mesonbuild.com/Fs-module.html#stem

meson: use fs.stem() to get the test name

---

src/dfuzzer.conf

Introduced in https://github.com/systemd/systemd/pull/29853.

dfuzzer.conf: suppress org.freedesktop.login1.Sleep()

---

src/suppression.c

[Fix build with -Werror=calloc-transposed-args](https://github.com/dbus-fuzzer/dfuzzer/commit/067939b97b7ed6a7877b6e9b566bc921befa8e23)
calloc() expects the number of elements as the first argument, and the
size of each element as the second one. Recent-enough gcc/clang started
warning about this, so let's fix the order of the arugments to avoid
build errors with -Werror.
```
[9/30] Compiling C object dfuzzer.p/src_suppression.c.o
../src/suppression.c: In function ‘df_suppression_load’:
../src/suppression.c:123:37: warning: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
123 |                 item = calloc(sizeof(*item), 1);
|                                     ^
../src/suppression.c:123:37: note: earlier argument …
```

Fix build with -Werror=calloc-transposed-args
